name: moevit
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - transformers
  - einops
  - tqdm
  - matplotlib
  - tensorboard
  - omegaconf
  - opencv
  - black
  - isort
  - jupyter
  - ipykernel
