model:
  name: moe_vit
  num_layers: 12
  embed_dim: 768
  num_heads: 12
  num_experts: 8
  top_k: 2
training:
  batch_size: 16
  epochs: 30
  learning_rate: 3e-4
dataset:
  name: TVQA
  video_resolution: 224
  patch_size: 16
  frames: 32


# Model Hyperparameters
model:
  embed_dim: 768
  num_layers: 12
  num_heads: 12
  video_patch_size: 16
  num_answer_classes: 500 # Example for TVQA
  max_seq_len: 256
  frames_per_video: 16
  moe:
    num_experts: 8
    top_k: 2
    # NEW SECTION: Add parameters for specialized experts
    experts:
      motion:
        flow_dim: 64
      fast_change:
        delta_dim: 32
      texture:
        # patch_size will be inherited from the main model config
        channels: 3


data:
  dataset_name: "tvqa"
  data_path: "/path/to/your/tvqa_dataset/" # You can keep your path
  batch_size: 32
  num_workers: 4
  text_tokenizer: "bert-base-uncased"